# Generated by Django 6.0.2 on 2026-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=400,
                null=True,
                verbose_name="id сессии",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=300,
                null=True,
                verbose_name="id сессии",
            ),
        ),
    ]
