# Generated by Django 6.0.2 on 2026-03-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
