# Generated by Django 6.0.2 on 2026-03-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=1000,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=500,
                null=True,
                verbose_name="id сессии",
            ),
        ),
    ]
